import Head from "next/head";
import { useState } from "react";
import Image from "next/image";
import {
  AiFillLinkedin,
  AiFillTwitterCircle,
  AiFillYoutube,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import deved from "../public/GusCircle.png";
import design from "../public/design.png";
import coding from "../public/coding.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-600">
        {/* navbar section */}
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl">Devop</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursive-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  href="#"
                  className="bg-gradient-to-b from-blue-500 to-blue-900 px-4 text-white py-2 rounded ml-8"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-blue-600 font-medium md:text-6xl">
              Gustavo Lago
            </h2>
            <h3 className="text-2xl py-2">WebDeveloper</h3>
            <p className="text-medium py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-yellow-50">
              Freelancer providing services for programming and content needs.
              Join me down below and let's get cracking!{" "}
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-yellow-50">
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillYoutube />
          </div>
          <div className="relative rounded-full w-80 h-80 mx-auto mt-20 overflow-hidden md:h-96 md:w-96">
            <Image src={deved} />
          </div>
        </section>
        {/* end of navbar section */}
        {/* Presentation section */}
        <section>
          <div>
            <h3 className="text-3xl py-2 text-center">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-yellow-50">
              Since de beginning of my journey as a Freelancer developer, I've
              done remote work for{" "}
              <span className="text-blue-600 dark:text-yellow-500">agencies</span> consulted for{" "}
              <span className="text-blue-600  dark:text-yellow-500">startups</span> and collaborated
              with talented people, to create digital products for both,
              business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-yellow-50">
              I offer a wide range of services, including brand design,
              programming and teaching
            </p>
          </div>
          {/* Card system */}
          <div className="lg:flex md:flex gap-10 justify-center">
            <div className="shadow-lg p-10 rounded-xl my-10 text-center mx-5">
              <Image src={design} />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Beautiful Designs
              </h3>
              <p className="py-2">
                Creating Elegant designs suited for your need
              </p>
              <h4 className="py-4 text-blue-600">Design tools</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Lightroom</p>
            </div>
            <div className="shadow-lg p-10 rounded-xl my-10 text-center mx-5">
              <Image src={coding} />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Beautiful Designs
              </h3>
              <p className="py-2">
                Creating Elegant designs suited for your need
              </p>
              <h4 className="py-4 text-blue-600">Design tools</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Lightroom</p>
            </div>
            <div className="shadow-lg p-10 rounded-xl my-10 text-center mx-">
              <Image src={consulting} />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Beautiful Designs
              </h3>
              <p className="py-2">
                Creating Elegant designs suited for your need
              </p>
              <h4 className="py-4 text-blue-600">Design tools</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Lightroom</p>
            </div>
          </div>
          {/* Card system */}
        </section>
        {/* End of presentation section */}
        <section>
          <div>
            <h3 className="text-3xl py-1">Portofolio</h3>
            <p className="text-md py-2 leading-8 text-center text-gray-800">
              Since de beginning of my journey as a Freelancer developer, I've
              done remote work for{" "}
              <span className="text-blue-600">agencies</span> consulted for{" "}
              <span className="text-blue-600">startups</span> and collaborated
              with talented people, to create digital products for both,
              business and consumer use.
            </p>
          </div>
          <div className="flex flex-col justify-center gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Image
                src={web1}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout={"resposive"}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web2}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout={"resposive"}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web3}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout={"resposive"}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web4}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout={"resposive"}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web5}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout={"resposive"}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web6}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout={"resposive"}
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
